name: Deploy to Firebase

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install @angular/cli
        run: npm i -D -E @angular/cli
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@master
        with:
          cordova-version: 8
      - name: Install app dependencies
        run: npm ci
      - name: Install functions dependencies
        run: cd functions && npm i && cd ..
      - name: 'Bump the version'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag:  'true'
      - name: Build prod app
        run: npm run build-app:prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy -P prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}