name: Build Prod App

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
      - run: npm ci
      - run: npm run build-app:prod